config/routes.rb
Rails.application.routes.draw do

  resources :dashboard, only: [:index]
  resources :expenses

  root 'dashboard#index'

  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :expenses, except: [:show, :edit, :new]
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController

  def index
    @handler = DashboardHandler.new(Expense.all)
    @amount_of_today = @handler.amount_of_today
    @amount_of_yesterday = @handler.amount_of_yesterday
    @amount_of_current_month = @handler.amount_of_current_month
    @amount_of_last_month = @handler.amount_of_last_month
  end
  
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/index.html.erb
<% provide(:page_title, "Dashboard") %>
<% provide(:dashboard_active, 'active') %>

<body class="full">

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="/">Conpital</a>

      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
          <li class="nav-item">
            <%= link_to "Dashboard", dashboard_index_path, class: "nav-link #{yield(:dashboard_active)}" %>
          </li>
          <li class="nav-item">
            <%= link_to "Expenses", expenses_path, class: "nav-link #{yield(:expenses_active)}" %>
          </li>
          <% if signed_in? %>
            <li class="nav-item"><%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %></li>
          <% else %>
            <li class="nav-item">
              <%= link_to "Log In", new_user_session_path, class: "nav-link #{yield(:login_active)}" %>
            </li>
            <li class="nav-item">
              <%= link_to "Sign Up", new_user_registration_path, class: "nav-link #{yield(:signup_active)}" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

<!-- Inicio Resumen -->
  <div class="container resumen text-center">
    <div class="row">
      <h5 class="col-3"><%= number_to_currency(@amount_of_today) %> COP</h5>
      <h5 class="col-3"><%= number_to_currency(@amount_of_yesterday) %> COP</h5>
      <h5 class="col-3"><%= number_to_currency(@amount_of_current_month) %> COP</h5>
      <h5 class="col-3"><%= number_to_currency(@amount_of_last_month) %> COP</h5>
    </div>
    <div class="row">
      <p class="col-3">TODAY</p>
      <p class="col-3">YESTERDAY</p>
      <p class="col-3">THIS MONTH</p>
      <p class="col-3">LAST MONTH</p>
    </div>
  </div>
<!-- Fin Resumen -->

<!-- Inicio Gráficos -->
  <div class="container">
    <div class="row">

      <h6 class="col-6 title">Last 6 months
        <%= column_chart  @handler.last_six_months_expenses_transaction_type_overview.joins(:transaction_type).group('transaction_types.name').group_by_month(:date, last: 6, format: "%B").count, stacked: true, colors: ["#379EAB", "#C24543", "#805F83", "#86B40B"] %>
        <!-- colors: Blue, Red, Purple, Green -->
      </h6>

     
      <h6 class="col-6 title">By day
        <%= column_chart @handler.this_month.joins(:transaction_type).group('transaction_types.name').group_by_day(:date, format: "%e").sum(:amount), colors: ["#379EAB", "#C24543", "#805F83", "#86B40B"] %>
        <!-- colors: Blue, Red, Purple, Green -->
      </h6>

    </div>
    <div class="row">

      <h6 class="col-6 title">By category
        <%= pie_chart @handler.this_month.joins(:transaction_type).group('transaction_types.name').count, donut: true, colors: ["#379EAB", "#C24543", "#805F83", "#86B40B", "#FEEA3A", "D6CFCF", "#FE3F80", "#009587"] %>
        <!-- colors: Blue, Red, Purple, Green, Yellow, Gray, Pink, Teal -->
      </h6>

      <h6 class="col-6 title">Accumulated
        <%=  area_chart [
          { name: "Current Month", data: @handler.this_month.group_by_day(:date).sum(:amount) },
          { name: "Last Month", data: @handler.last_month.group_by_day(:date).sum(:amount) }
        ]%>
      </h6>

    </div>
  </div>
<!-- Fin Gráficos -->

</body>